### ISSUE TITLE
Switch the LCD shift register to an ST part.

### ISSUE THREAD

**Issue by aithon** [aithon/aithon#15]
We are currently using an NXP part.  This may change the package of the 74HC164.

**Comment by cccitron** [comment]
Would a STPIC6D595 or a STPIC6C595 be a good replacement? What's the best way to compare them to the part that's already on the board?

**Comment by aithon** [comment]
We want to use the same 74hc164, but an ST version.

**Comment by bgomberg** [comment]
Looks like those are both for 5V logic which may or may not work with the
3.3V signal from the microcontroller. It is also open drain which means
we'd have to add 8 more resistors (one for each output). The ones that are
similar to what we are using seem to be end-of-life.

I guess those are the only options if we want to use an ST part though. We
could use them with a 3.3V->5V level shifter to be safe.

**Comment by bgomberg** [comment]
I couldn't find any ST level shifters on Mouser though. We could try running it directly at 3.3V logic - it should be fine.

**Comment by bgomberg** [comment]
Actually, I think either of those parts will be fine (not sure what the difference between the two is). What we can do is add 10k pull-up resistors which pull up the logic lines which go out of the microcontroller to the shift register pins to 5V, and then run the microcontroller outputs as open drain, essentially giving us 5V logic out of the microcontroller. I can help with the schematic of this.

**Comment by bgomberg** [comment]
We'll keep the same part as per our call this morning.
