### ISSUE TITLE
Rename the ICs on the schematic

### ISSUE THREAD

**Issue by aithon** [aithon/aithon#18]
We need to remove the default names of:  U$3, U$4.  It can get confusing with a U3 and U$3.

**Comment by cccitron** [comment]
Here are the new IC names
U$3 -> U15
U2
U3
U$4 -> U4
U$5 -> U5
U6 -> U12
U8 -> U13
U$2 -> U14
U$1 -> U1
U$10 -> U10
U$11 -> U11
U$6 -> U6
U$7 -> U7
U$8 -> U8
U$9 -> U9
U$12 -> U16

NOTE: The Oct 2nd BOM listed U$12 (schematic) as Q1 (excel).
