### ISSUE TITLE
add pin 1 marking to all ICs

### ISSUE THREAD

**Issue by aithon** [aithon/aithon#24]

**Comment by aithon** [comment]
Can you recheck the LSM330DLC?  I think the marking is incorrect.  Also, could you list which chips were modified?

**Comment by cccitron** [comment]
Good catch, I didn't realize that was the bottom view on the datasheet.

Modified chips:
U$6, U$7, U$8, U$9 - value: SI7617, library: r_cubed, package: POWERPAK1212-8
U$1 - value: LSM330DLC, library: r_cubed, package: LGA-28
U$3 - value: MC74HC164, library: r_cubed, package: TSSOP-14
IC4 - value: LM358DT, library: linear, package: SO08

Need modification:
U6 & U8 - SOT23-6L. I don't have this part in my library. They also need a silkscreen line around them.

**Comment by cccitron** [comment]
Found the library for SOT23-6L, will update afterwards.

**Comment by cccitron** [comment]
Modified:
U6 & U8 - SOT23-6L package is for USBLC6-2.
U$2 - package: 8-SOIC, value: STMPS2171MTR
