### ISSUE TITLE
look into protection for the gate of U$9 (Si7617)

### ISSUE THREAD

**Issue by aithon** [aithon/aithon#27]
The gate of Si7617 is directly connected to RAW_SPWR.  Some mishandling/misuse of the external servo power may damage the gate of the MOSFET.

**Comment by cccitron** [comment]
How's this Zener Diode look?
http://www.mouser.com/ProductDetail/Vishay-Semiconductors/BZX384C20-E3-08/?qs=sGAEpiMZZMvNv09GOMabnXDcNt4VcqlR
