### ISSUE TITLE
Update Aithon Library for New Rev1 Board

### ISSUE THREAD

**Issue by aithon** [aithon/aithon#36]
We will need to update ChibiOS to include the new STM32F437 support as well as update all the board files with the new pin-outs. We will also likely need to add / modify library functions to support all the changed (and new) functionality we've made with the latest revision.

**Comment by bgomberg** [comment]
I've edited this issue to include everything we'll need to change in the library to get it to work with the new Rev1 boards.

**Comment by bgomberg** [comment]
Going to close this since everything's updated, there's just some issues with the code that still need to be worked out in general.
