### ISSUE TITLE
Change regulator to ST part

### ISSUE THREAD

**Issue by aithon** [aithon/aithon#44]
PM6685   http://www.st.com/web/en/resource/technical/document/datasheet/CD00068881.pdf

dual N-MOSFET
http://www.st.com/st-web-ui/static/active/en/resource/technical/document/datasheet/CD00268229.pdf

inductor 1
http://www.mouser.com/ProductDetail/AVX/LMIP7070M1R5AT3S/?qs=sGAEpiMZZMv126LJFLh8y0%2fl6h0%252bCpC2OFLNcjOwQps%3d

inductor 2
http://www.mouser.com/ProductDetail/Sumida/0520CDMCDS-3R3MC/?qs=sGAEpiMZZMsg%252by3WlYCkU9ppYVJOsp0z%252bGL2yF6iw5M%3d

Schottky diode
http://www.st.com/st-web-ui/static/active/en/resource/technical/document/datasheet/CD00003014.pdf

**Comment by bgomberg** [comment]
Dual Shottky for BOOT pins:
http://www.mouser.com/ProductDetail/STMicroelectronics/BAS70-06FILM/?qs=%2fha2pyFadujS4XySZlZcfUFTXjb0%2fTKHLVoSUV%2fHsUiOFQoCabda9A%3d%3d
