### ISSUE TITLE
modify jedit installation JAR

### ISSUE THREAD

**Issue by aithon** [aithon/aithon#6]
add the Aithon.jar plugin to the jedit installation JAR and test the installation.

**Comment by aithon** [comment]
I believe the JAR is signed somehow and that is preventing me from modifying the JAR for a release.  Would it be okay to have users install the stock jEdit and then run our own small installer JAR?

**Comment by bgomberg** [comment]
What would the steps for this be exactly? Would it be possible to package the jEdit jar and our plugin jar together somehow and have a jar that does the setup (or something similar)?

**Comment by aithon** [comment]
I was able to build a Mac installer for jEdit 5.1.1 (latest stable).  I inserted a test file into the installer and that was installed when running the installer.
