### ISSUE TITLE
Analog pin ordering should match others

### ISSUE THREAD

**Issue by aithon** [aithon/aithon#64]
I think the analog headers should match the digital pin headers.  I know it is easier to layout on the PCB, but I think it will cause confusion when connecting sensors.

**Comment by bgomberg** [comment]
You mean with respect to GND/PWR/SIG or the numbers?

**Comment by jsseng** [comment]
The GND/PWR/SIG.

On Tue, May 5, 2015 at 9:24 PM, bgomberg notifications@github.com wrote:

> You mean with respect to GND/PWR/SIG or the numbers?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aithon/aithon/issues/64#issuecomment-99317630.

## 

John Seng
CSC Dept.
Cal Poly State University
