### ISSUE TITLE
battery voltage monitoring should be enabled by default

### ISSUE THREAD

**Issue by aithon** [aithon/aithon#65]
I was thinking that 90% of users would like battery monitoring instead of having a 14th analog input.  I think that maybe battery monitoring should be enabled by default and we take away 1 of the analog inputs.  I could see someone connecting a sensor to analog 0 when battery monitoring is enabled.  We should prevent that error, by keeping the circuit separate.

**Comment by bgomberg** [comment]
I added another pin to the shield to grab analog A14 and connected the battery voltage to that instead. On the Uno, they probably won't want to use an analog input for battery voltage anyways. If they do, they can always run a wire from the exposed header.
