### ISSUE TITLE
add autodetect mode to Uploader

### ISSUE THREAD

**Issue by aithon** [aithon/aithon#8]
add a way to detect an Aithon board

**Comment by bgomberg** [comment]
You mean have the uploader figure out what COM port the Aithon board is on automatically?

**Comment by aithon** [comment]
Yes, I was thinking that.  I can think of how to do that on Mac and Linux, but I don't know enough about Windows.

**Comment by bgomberg** [comment]
You could do it by scanning all the COM ports, but that's pretty slow.

**Comment by aithon** [comment]
Once it is detected in Control Panel, could you read it from there?

**Comment by bgomberg** [comment]
That's basically the same thing.

**Comment by bgomberg** [comment]
This is now done.
